worker_processes 1;
events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  applicationoctet-stream;

    server {
        listen 8080;
        server_name vpn.googleapis.com;

        location vless {
            proxy_pass http://127.0.0.1:3001;  # sing-box listens here
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection upgrade;
            proxy_set_header Host $host;
        }

        location  {
            return 200 'OK';
            add_header Content-Type textplain;
        }
    }
}
